### ISSUE TITLE
ERROR:Fail to create a client session: client() got an unexpected keyword argument 'access_key_id'

### ISSUE THREAD

**Issue by lc6chang** [awslabs/amazon-s3-data-replication-hub-plugin#16]
**Describe the bug**
I follow the README on this [commit 00a6a20](https://github.com/awslabs/amazon-s3-data-replication-hub-plugin/tree/00a6a20ed143c7b315fc9e1675ae00fe6fe2ddff) to deploy a stack to sync data from AWS China to AWS Global. Then, when CloudWatch triggers that event, ECS Job Sender Task failed and told me
```
ERROR:Fail to create a client session: client() got an unexpected keyword argument 'access_key_id' 
```
**To Reproduce**
First, prepare a parameter in SSM Parameter Store:
```json
{
  "access_key_id": "<Your Access Key ID>",
  "secret_access_key": "<Your Access Key Secret>"
}
```
Then, click **Launch Stack** button [here](https://github.com/awslabs/amazon-s3-data-replication-hub-plugin/tree/00a6a20ed143c7b315fc9e1675ae00fe6fe2ddff#deploy-via-aws-cloudformation) in AWS Standard Partition to create a new stack, with a bucket in AWS China as the source.

**Expected behavior**
Error should not be raised.

**Screenshots**
![image](https://user-images.githubusercontent.com/37406349/105938472-97034e00-6092-11eb-9b10-19a32c0245c4.png)

**Please complete the following information about the solution:**
- [x] Version: [00a6a20]
- [x] Region: [us-west-2]
- [x] Was the solution modified from the version published on this repository? **No**
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [x] Were there any errors in the CloudWatch Logs? Yes. Pasted in **Screenshots**.

**Additional context**
It has been fixed after I added a prefix `aws_` in the Parameter Store credential
```json
{
  "aws_access_key_id": "<Your Access Key ID>",
  "aws_secret_access_key": "<Your Access Key Secret>"
}
```

**Comment by daixba** [comment]
Hi @lc6chang , 

I am not able to reproduce this issue. The ssm parameter format with *"access_key_id"* is correct, and I don't see other customers having the same issue.

`aws_access_key_id/aws_secret_access_key` is the standard options for AWS S3 SDK, the reason why we remove `aws_` is that we supports many other cloud services as well, they might support S3 SDK as well, but to avoid confusion,  we just use general "access_key_id" and "secret_access_key"

If you added the prefix, it still works here, because from the backend,  we were doing the same in the code, we also renamed the keys with prefix `aws_`

You can maybe retry the deployment again if needed. Thanks for using this solution.

**Comment by lc6chang** [comment]
@daixba very very interesting. I've also looked into your code, exactly you renamed the keys with prefix `aws_`. And I tested again just now, the error disappeared😂. Anyway it works well right now haha. Thanks again, your project helps me too much! 🚀
